FROM node:16.14-alpine
# Mudar para o diretório de trabalho /app-backend
WORKDIR /frontend
# Copiar os package.json, package-lock.json e packages.npm para o container
COPY . .
# Instalar as dependências Node
RUN npm install
# Copiar o restante dos arquivos da aplicação para o container
COPY . .
# Sinalize que aplicação expõe a porta 3001
EXPOSE 3000
# Configurar os comandos para iniciar a aplicação de acordo com as boas práticas
CMD [ "npm", "start" ]
# Dica: Leia a seção Docker e Docker-compose no README para mais informações